name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.9.4
        otp-version: 22.2
    - name: deps cache
      uses: actions/cache@v1
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
        restore-keys: |
          ${{ runner.os }}-mix-
    - name: build cache
      uses: actions/cache@v1
      with:
        path: _build
        key: ${{ runner.os }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
        restore-keys: |
          ${{ runner.os }}-build-
    - name: dializer cache
      uses: actions/cache@v1
      with:
        path: deps
        key: ${{ runner.os }}-plts
        restore-keys: |
          ${{ runner.os }}-plts
    - name: Install Dependencies
      run: mix deps.get
    - name: Check Format
      run: mix format --check-formatted
    - name: Run Tests
      run: MIX_ENV=test mix coveralls.xml -u
    - name: Run credo
      run: mix credo
    - name: Run dialyzer
      run: mix dialyzer
    - name: Run sobelow
      run: mix sobelow
